### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by boehser-enkel** [ms-jpq/docker-time-machine#12]
Set up via the docker compose script.
Error: com.apple.TimeMachine.Settings-Extension-Error5

```
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      USER: pi
      PASS: schulleder6
    ports:
      - 445:445
    volumes:
      - ./samba:/storage
    restart: on-failure 
```
